### ISSUE TITLE
Revision Numeros Complejos

### ISSUE THREAD

**Issue by Janucas** [Janucas/PuestaAlDia#3]
Te dejo el codigo del ejercicio numeros complejos, a parte te subire esta tarde al correo una foto de un problemilla que no entiendo con el git.

Me gustaria saber cuales son los proximos ejercicios con los que vamos a trabajar.

Y tambien me gustaria saber si para los que estamos haciendo la puesta al dia va a haber un examen distinto al del resto de la clase acorde a lo que estamos trabajando nosotros ahora.

Un saludo.

**Comment by ioliasa** [comment]
En complejo en suma creo que te falta un paréntesis. La resta no está terminada y no veo el main. Por lo demás tienes que seguir trabajando el resto de ejercicios, y sí, os haré otro examen a ustedes, pero tenéis que darle más caña, si no, no llegamos.

**Comment by Janucas** [comment]
Debió haber un problema en la subida el otro día ya que no he escrito ningún código y esto que te subo hoy es lo que ya tenia el viernes
